In [4]:
#find the root of x+cos(x)
from scipy.optimize import root
from math import cos
def eqn(x):
    return x+cos(x)
myroot=root(eqn,0)
print(myroot.x)
#printing all the information
print(myroot)

[-0.73908513]
    fjac: array([[-1.]])
     fun: array([0.])
 message: 'The solution converged.'
    nfev: 9
     qtf: array([-2.66786593e-13])
       r: array([-1.67361202])
  status: 1
 success: True
       x: array([-0.73908513])


In [10]:
# Minimize the function x^2 + x + 2 with BFGS
from scipy.optimize import minimize
def eqn(x):
    return x**2 + x + 2
mymin = minimize(eqn, 0, method='BFGS')
print(mymin)


      fun: 1.75
 hess_inv: array([[0.50000001]])
      jac: array([0.])
  message: 'Optimization terminated successfully.'
     nfev: 8
      nit: 2
     njev: 4
   status: 0
  success: True
        x: array([-0.50000001])


In [1]:
#csr_matrix
import numpy as np
from scipy.sparse import csr_matrix
arr=np.array([0,0,0,0,0,1,1,0,2])
print(csr_matrix(arr))

  (0, 5)	1
  (0, 6)	1
  (0, 8)	2


In [2]:
#viewing non zero using data property
import numpy as np
from scipy.sparse import csr_matrix
arr=np.array([0,0,0,0,0,1,1,0,2])
print(csr_matrix(arr).data)

[1 1 2]


In [4]:
#counting non_zero
import numpy as  np
from scipy.sparse import csr_matrix
arr=np.array([[0,0,0],[0,6,0],[0,2,1]])
print(csr_matrix(arr).count_nonzero())

3


In [6]:
import numpy as  np
from scipy.sparse import csr_matrix
arr=np.array([[0,0,0],[0,6,0],[0,2,1]])
mat=csr_matrix(arr)
mat.eliminate_zeros()
print(mat)

  (1, 1)	6
  (2, 1)	2
  (2, 2)	1


In [7]:
import numpy as  np
from scipy.sparse import csr_matrix
arr=np.array([[0,0,0],[0,6,0],[0,2,1]])
print(csr_matrix(arr).tocsc())


  (1, 1)	6
  (2, 1)	2
  (2, 2)	1


In [8]:
#adjacency matrix
from scipy.sparse  import csr_matrix
from scipy.sparse.csgraph import connected_components
import numpy as np
arr=np.array([[0,0,0],[2,0,3],[6,0,2]])
new_arr=csr_matrix(arr)
print(connected_components(new_arr))

(1, array([0, 0, 0]))


In [12]:
#Find the shortest path from element 1 to 2:
import numpy as  np
from scipy.sparse import csr_matrix
from scipy.sparse.csgraph import dijkstra
arr=np.array([[0,0,0],[0,6,0],[0,2,1]])
mat=csr_matrix(arr)
print(dijkstra(mat, return_predecessors=True,indices=0))

(array([ 0., inf, inf]), array([-9999, -9999, -9999]))


In [13]:
#finding the shortest path between all pairs elements
import numpy as np
from scipy.sparse.csgraph import floyd_warshall
from scipy.sparse import csr_matrix
arr=np.array([[0,0,0],[0,6,0],[0,2,1]])
mat=csr_matrix(arr)
print(floyd_warshall(mat, return_predecessors=True))


(array([[ 0., inf, inf],
       [inf,  0., inf],
       [inf,  2.,  0.]]), array([[-9999, -9999, -9999],
       [-9999, -9999, -9999],
       [-9999,     2, -9999]]))


In [14]:
import numpy as  np
from scipy.sparse import csr_matrix
from scipy.sparse.csgraph import bellman_ford
arr=np.array([[0,0,0],[0,-6,0],[0,2,1]])
mat=csr_matrix(arr)
print(bellman_ford(mat, return_predecessors=True,indices=0))

(array([ 0., inf, inf]), array([-9999, -9999, -9999]))


In [15]:
import numpy as  np
from scipy.sparse import csr_matrix
from scipy.sparse.csgraph import depth_first_order
arr=np.array([[0,2,0],[0,6,0],[0,2,1]])
mat=csr_matrix(arr)
print(depth_first_order(mat,2 ))

(array([2, 1]), array([-9999,     2, -9999]))


In [16]:
import numpy as  np
from scipy.sparse import csr_matrix
from scipy.sparse.csgraph import breadth_first_order
arr=np.array([[0,2,0],[0,6,0],[0,2,1]])
mat=csr_matrix(arr)
print(breadth_first_order(mat,2 ))

(array([2, 1]), array([-9999,     2, -9999]))


In [17]:
#triangulation
import numpy as  np
from matplotlib import pyplot as plt
from scipy.spatial import Delaunay
arr=np.array([[2,4],[3,4],[3,0],[2,2],[4,1]])
simplices=Delaunay(arr).simplices
plt.triplot=(arr[:, 0], arr[:, 1], simplices)
plt.scatter=(arr[:, 0], arr[:, 1])
plt.show()


In [21]:
#KDTrees
#find the nearest neighbor to point(3,6)
from scipy.spatial import KDTree
points=[(1,-1),(2,3),(3,-5),(4,6)]
kdtree=KDTree(points)
quiz=kdtree.query((3,6))
print(quiz)

(1.0, 3)


In [25]:
#distance metrics
#euclidean distance
#find the euclidean distance between two points
from scipy.spatial.distance import euclidean
p1=(16,10)
p2=(10,20)
res=euclidean(p1,p2)
print(res)


11.661903789690601


In [26]:
#cityblock distance
from scipy.spatial.distance import cityblock
p1=(2,7)
p2=(4,8)
dist=cityblock(p1,p2)
print(dist)

3


In [27]:
#cosine distance
from scipy.spatial.distance import cosine
p1=(2,7)
p2=(4,8)
dist=cosine(p1,p2)
print(dist)

0.01712781306567812


In [28]:
#hamming distance
#find the hamming distance between given points
from scipy.spatial.distance import hamming
p1=(True,False,True)
p2=(False,False,True)
dist=hamming(p1,p2)
print(dist)

0.3333333333333333


# matlab arrays

In [30]:
from scipy import io
import numpy as np
arr=np.array(10)
io.savemat("arr.mat",{'vec':arr})

In [31]:
#import the array from the following mat file
from scipy import io
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
#exporting
io.savemat("arr.mat",{'vec':arr})
#importing
data=io.loadmat('arr.mat')
print(data)


{'__header__': b'MATLAB 5.0 MAT-file Platform: nt, Created on: Tue Jan 10 08:28:41 2023', '__version__': '1.0', '__globals__': [], 'vec': array([[1, 2, 3, 4, 5, 6, 7]])}


In [32]:
print(data['vec'])

[[1 2 3 4 5 6 7]]


In [33]:
#the output above changes from 1-D to 2-D to solve this
#we can pass another argument
data=io.loadmat('arr.mat',squeeze_me=True)
print(data['vec'])

[1 2 3 4 5 6 7]


# interpolation

In [44]:
#interpolation of 1-D
from scipy.interpolate import interp1d
import numpy as np
xs=np.arange(10)
ys=2*xs +1
interp_func=interp1d(xs,ys)
newarr=interp_func(np.arange(2.1,4,0.1))
print(newarr)

[5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.  7.2 7.4 7.6 7.8 8.  8.2 8.4 8.6
 8.8]


In [47]:
from scipy.interpolate import UnivariateSpline
import numpy as np
xs=np.arange(10)
ys=2**xs + np.sin(xs)+1
interp_func=UnivariateSpline(xs,ys)
newarr=interp_func(np.arange(2.1,4,0.1))
print(newarr)

[ 5.6998881   5.91561217  6.15684727  6.42650265  6.72748754  7.06271116
  7.43508274  7.84751152  8.30290673  8.80417759  9.35423334  9.95598321
 10.61233642 11.32620221 12.10048981 12.93810845 13.84196736 14.81497576
 15.86004289]


# statistical description of data

In [48]:
#show the statistical description of the velues in an array
import numpy as np
from scipy.stats import describe
v=np.random.normal(size=100)
test=describe(v)
print(test)

DescribeResult(nobs=100, minmax=(-1.8866964220399514, 1.9923451442386948), mean=-0.0350229981640833, variance=0.8403551385371084, skewness=0.1835999157761776, kurtosis=-0.5631762198590091)


# skewness and kurtosis

In [49]:
import numpy as np
from scipy.stats import skew,kurtosis
v=np.random.normal(size=100)
print(skew(v))
print(kurtosis(v))
#from the  output the skewness is at right
#from the output the kurtosis is lightly tailed

0.0749892181330708
-0.1090101744754497
